# Generated by Django 4.2.7 on 2023-12-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_rename_phone_number_farmers_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
    ]
