# Generated by Django 4.2.7 on 2023-12-11 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_alter_farmers_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='phoneNumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must contain only numeric characters.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
